# Intern Assessment Question 1
**Yuzhou Liu**

## Part A 
**Wrangle Subscribers Data**

In [0]:
# Packages Used
import pandas as pd
import numpy as np

### 1. Load data directly from the provided URL instead of downloading and loading as csv (file size: ~ 180MB)

In [0]:
# Load Subscripers Data
subscriper_df = pd.read_csv("https://s3.amazonaws.com/orim-misc-data/assessment/subscribers.csv ")

In [228]:
df = subscriper_df.copy()
df.head()

                 Profile.Id  ...                                    ebb_preferences
0  5572fb5592721912198b587b  ...  ["bestsellers","mysteries_thrillers_true_crime...
1  5441111b66dfa5ab01b0a000  ...                                                NaN
2  56cde9d9d9cb94486d8b51d7  ...                                                NaN
3  57e68298d9cb942a708b48db  ...                  ["bestsellers","book_club_picks"]
4  5498bd77f641910f100e23fb  ...                                                NaN

[5 rows x 21 columns]

### 2. Count number of subscribers we acquired each year and month by referral source

In [0]:
# Get Year and Month from Signup Date column
df['Signup'] = pd.to_datetime(df['Signup'])
df['Year'] = df['Signup'].dt.year
df['Month'] = df['Signup'].dt.month

In [230]:
# All NA referral source means that people signed up the newsletter from an organic source
df['referral_source'].fillna('OrganicSource', inplace = True)

# Get rid of all punctuations and whitespce, also to lower case
df['referral_source']=df['referral_source'].str.lower().str.replace('[^\w]|_','')

# Check if there is still issues left
set(df['referral_source'].unique())

{'adroll',
 'aramis',
 'bookbub',
 'bookpage',
 'bookriot',
 'bookriotsweeps',
 'bookstr',
 'cerkl',
 'chickensoup',
 'dmi',
 'dmiqhealth',
 'dunkindonuts',
 'earlybirdbooks',
 'ebbembed',
 'ebbv2',
 'emailcampaign',
 'facebook',
 'facebookcom',
 'facebookleads',
 'fbgiveaways',
 'fyntr',
 'google',
 'humblebundle',
 'inbookad',
 'instafreebie',
 'jbfmembers',
 'litbreaker',
 'lithub',
 'litsy',
 'liveintent',
 'newvalue',
 'noisetrade',
 'offtheshelf',
 'optint',
 'organicsource',
 'paypal',
 'peachtree',
 'permissiondata',
 'pinterest',
 'pinterestcom',
 'portalist',
 'quora',
 'ralphcom',
 'ralphtest',
 'readitforward',
 'reddit',
 'sailthru',
 'shelfawareness',
 'shelfie',
 'standarddisplay',
 'swagbucks',
 'taboola',
 'tafemail',
 'test',
 'thelineup',
 'tiburon',
 'tlu',
 'tlucheckbox',
 'torsweeps',
 'twitter',
 'untagged',
 'viber',
 'warisboring',
 'welcomeemail',
 'worth',
 'worthbooks'}

In [0]:
# The following aggregations is based on my personal knowledge and understanding
    # 'bookriots' and 'bookriotsweep' are the same source from 'bookriot.com'
    # facebook','facebookcom' and 'facebookleads' are the same source from 'facebook.com'
    # 'pinterest' and 'pinterestcom' are the same source from 'pinterest.com'
df['referral_source'] = df['referral_source'].str.replace('pinterestcom','pinterest').str.replace('bookriotsweeps','bookriot').str.replace('facebookleads|facebookcom','facebook',regex=True)

In [232]:
count_sub = pd.pivot_table(df, values='Profile.Id', 
                           index=['Year', 'Month'],
                           columns=['referral_source'],
                           aggfunc=np.count_nonzero,
                           fill_value = 0)
count_sub

referral_source  adroll  aramis  bookbub  ...  welcomeemail  worth  worthbooks
Year Month                                ...
2014 6                0       0        0  ...             0      0           0
     7                0       0        0  ...             1      0           0
     8                0       0        0  ...             6      0           0
     9                1       1        2  ...             6      0           0
     10               0       1        0  ...             1      0           0
     11               1       0        0  ...             0      0           0
     12               3       4        0  ...             2      0           1
2015 1                0       2        0  ...             3      0           0
     2                0       1        1  ...             2      0           0
     3                0       1        0  ...             1      0           0
     4                0       2        0  ...             0      0           0
     5                0       0        0  ...             0      0           0
     6                0      14        0  ...             3      0           0
     7                0       4        0  ...             0      0           0
     8                0      14        0  ...             0      1           0
     9                0      17        1  ...             2      0           0
     10               0       0        1  ...             2      0           0
     11               0       1        0  ...             2      0           0
     12               0       9        0  ...             1      0           0
2016 1                0      55        1  ...             6      0           0
     2                0      36        1  ...             5      0           0
     3                0      47        0  ...             3      1           1
     4                0      40        1  ...             3      0           0
     5                0    1883        1  ...             0      2           0
     6                0       0        2  ...             6      0           0
     7                0       0      161  ...             4      0           1
     8                0       0        0  ...            12      0           0
     9                0       0        0  ...            32      0           0
     10               0       0        0  ...            73      0           1
     11               0       0        0  ...            68      0           0
     12               0       0        0  ...            82      0           0
2017 1                0       0        0  ...           119      0           3
     2                0       0        0  ...            96      0           6
     3                0       0        0  ...            96      0           1
     4                0       0        0  ...            57      0           6

[35 rows x 62 columns]

### 3. Create a new column counting number of preferences subscribers select. If the value of ebb_preference is empty, subscriber will receive all the genres that are available.

In [233]:
# Find all the genres
# genres are seperated with commas (need get rid of all other punctuations beforehand)
ebb = df['ebb_preferences'].dropna().str.lower().str.replace('[^\w,]|_','').str.replace(',',' ')
genre = set(x for l in ebb.str.split() for x in l)

# Check if there are issues
genre

{'bestsellers',
 'biographiesandmemoir',
 'biographyandmemoir',
 'bookclubpicks',
 'c',
 'ch',
 'chi',
 'chil',
 'child',
 'childr',
 'childre',
 'children',
 'childrens',
 'g',
 'ge',
 'gen',
 'gene',
 'gener',
 'genera',
 'general',
 'generaln',
 'generalno',
 'generalnon',
 'generalnonf',
 'generalnonfi',
 'generalnonfic',
 'generalnonfict',
 'generalnonficti',
 'generalnonfictio',
 'generalnonfiction',
 'hist',
 'historicalfiction',
 'history',
 'life',
 'lifestyl',
 'lifestylean',
 'lifestyleand',
 'lifestyleandc',
 'lifestyleandco',
 'lifestyleandcooki',
 'lifestyleandcookin',
 'lifestyleandcooking',
 'literaryfic',
 'literaryfiction',
 'mysteries',
 'mysteriesth',
 'mysteriesthri',
 'mysteriesthrill',
 'mysteriesthrillers',
 'mysteriesthrillerst',
 'mysteriesthrillerstr',
 'mysteriesthrillerstru',
 'mysteriesthrillerstruec',
 'mysteriesthrillerstruecr',
 'mysteriesthrillerstruecri',
 'mysteriesthrillerstruecrim',
 'mysteriesthrillerstruecrime',
 'null',
 'p',
 'po',
 'poe',
 'poet',
 'poetr',
 'poetry',
 'r',
 'ro',
 'rom',
 'roma',
 'roman',
 'romanc',
 'romance',
 's',
 'sc',
 'sci',
 'scie',
 'scien',
 'scienc',
 'science',
 'sciencef',
 'sciencefi',
 'sciencefic',
 'sciencefict',
 'scienceficti',
 'sciencefictio',
 'sciencefiction',
 'sciencefictionf',
 'sciencefictionfa',
 'sciencefictionfan',
 'sciencefictionfant',
 'sciencefictionfanta',
 'sciencefictionfantas',
 'sciencefictionfantasy',
 'someebbpref',
 'thrillers',
 'thrillerstruecrime',
 'truecrime',
 'y',
 'yo',
 'you',
 'youn',
 'young',
 'younga',
 'youngad',
 'youngadu',
 'youngadul',
 'youngadult'}

In [234]:
# Several Issues here
    # 'null' and 'someebbpref' need to be treated the same as Nan
    # 'biographies' and 'biography' need to be treated the same
    # 'hist' and 'history' need to be treated the same
    # There some genres only showing part of the word, like 'childerns'
        # all genre start with 'c' count as 'childerns'
        # all genre start with 'g' count as 'generalnonfiction'
        # all genre start with 'life' count as 'lifestyleandcooking'
        # all genre start with 'liter' count as 'literaryfiction'
        # all genre start with 'myster' count as 'mysteriesthrillerstruecrime'
        # all genre start with 'p' count as 'poetry'
        # all genre start with 'r' count as 'romance'
        # all genre start with 's' count as 'sciencefictionfantasy'
        # all genre start with 't' count as 'thrillerstruecrime'
        # all genre start with 'y' count as 'youngadult'
    

# Fixing issues
def Fixing(ebb):
  ebb = ebb.str.lower().str.replace('[^\w,]|_','').str.replace(',',' ')
  ebb = ebb.str.replace('someebbpref','').str.replace('biographies','biography').str.replace('history','hist').str.replace('null','')
  ebb = ebb.str.replace(r'\b([c]\w+)\b|\b([c])\b','childrens',regex = True)
  ebb = ebb.str.replace(r'\b([g]\w+)\b|\b([g])\b','generalnonfiction',regex = True)
  ebb = ebb.str.replace(r'\b([life]\w+)\b','lifestyleandcooking',regex = True)
  ebb = ebb.str.replace(r'\b([liter]\w+)\b','literaryfiction',regex = True)
  ebb = ebb.str.replace(r'\b([myster]\w+)\b','mysteriesthrillerstruecrime',regex = True)
  ebb = ebb.str.replace(r'\b([p]\w+)\b|\b([p])\b','poetry',regex = True)
  ebb = ebb.str.replace(r'\b([r]\w+)\b|\b([r])\b','romance',regex = True)
  ebb = ebb.str.replace(r'\b([s]\w+)\b|\b([s])\b','sciencefictionfantasy',regex = True)
  ebb = ebb.str.replace(r'\b([t]\w+)\b|\b([t])\b','thrillerstruecrime',regex = True)
  ebb = ebb.str.replace(r'\b([y]\w+)\b|\b([y])\b','youngadult',regex = True)
  ebb = ebb.str.split()
  return ebb

ebb = df['ebb_preferences'].dropna()
ebb = Fixing(ebb)
genre = set(x for l in ebb for x in l)

# Check Again
genre

{'bestsellers',
 'biographyandmemoir',
 'bookclubpicks',
 'childrens',
 'generalnonfiction',
 'hist',
 'historicalfiction',
 'literaryfiction',
 'mysteriesthrillerstruecrime',
 'poetry',
 'romance',
 'sciencefictionfantasy',
 'youngadult'}

In [0]:
# Alter the DataFrame
genre_str = str(genre)
# If the value of ebb_preference is empty, subscriber will receive all the genres that are available.
ebb = df['ebb_preferences'].fillna(genre_str)
df['ebb_preferences'] = Fixing(ebb)
df['ebb_preferences'] = df['ebb_preferences'].apply(np.array)

In [236]:
df[['ebb_preferences']].head()

                                     ebb_preferences
0  [bestsellers, mysteriesthrillerstruecrime, mys...
1  [childrens, hist, generalnonfiction, mysteries...
2  [childrens, hist, generalnonfiction, mysteries...
3                       [bestsellers, bookclubpicks]
4  [childrens, hist, generalnonfiction, mysteries...

In [237]:
# Create a new column counting number of preferences subscribers select.
def uniquecount(array):
  num = len(np.unique(array))
  return num
  
df['#ofPreferences'] = df['ebb_preferences'].apply(uniquecount)

# Check
df.iloc[:5,-10:]

  Top.Device referral_source first_name  ...  Year  Month #ofPreferences
0      Other             dmi      Betty  ...  2015      6              4
1        NaN        untagged        NaN  ...  2014     10             10
2        NaN             dmi        Ana  ...  2016      2             10
3        NaN        facebook        NaN  ...  2016      9              2
4    Android   organicsource        NaN  ...  2014     12             10

[5 rows x 10 columns]

### 4. Convert ebb_preference column values into their own binary columns.

In [0]:
genre = list(genre)

In [239]:
def covertbinary(body, key):
  ans = int(key in body)
  return ans
for i in genre:
  df[i] = df['ebb_preferences'].apply(covertbinary, key = i)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

In [240]:
# Check
df.iloc[:5,-20:]

  last_name  age gender  ... biographyandmemoir  youngadult  literaryfiction
0   Goodwin  NaN    NaN  ...                  0           0                1
1       NaN  NaN    NaN  ...                  1           0                1
2   Alvarez  NaN    NaN  ...                  1           0                1
3       NaN  NaN    NaN  ...                  0           0                0
4       NaN  NaN    NaN  ...                  1           0                1

[5 rows x 20 columns]

## Part B (optional)
**forecasting model**

In [0]:
#from google.colab import drive
#drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
"""
import pickle
pickle_out = open('/content/drive/My Drive/Challenges/InternCh/Question1/Subscribers.pkl', 'wb')
pickle.dump(df,pickle_out)
pickle.dump(df,pickle_out)
pickle_out.close()

"""

In [0]:
# Read in Cleaned Dataset

"""
import pickle
pickle_in = open('/content/drive/My Drive/Challenges/InternCh/Question1/Subscribers.pkl', 'rb')
df_original = pickle.load(pickle_in)
pickle_in.close()
df_original.head()

"""

                 Profile.Id  ... sciencefictionfantasy
0  5572fb5592721912198b587b  ...                     0
1  5441111b66dfa5ab01b0a000  ...                     0
2  56cde9d9d9cb94486d8b51d7  ...                     0
3  57e68298d9cb942a708b48db  ...                     0
4  5498bd77f641910f100e23fb  ...                     0

[5 rows x 37 columns]

In [0]:
# Pakage Used
import pandas as pd
import numpy as np

### Data Preprocessing

In [242]:
# Remove Features that obviously cannot contribute to forecasting
# Id is unique
# Names (First and Last) not helping
# Year,Month is derived from Signup Date
# ebb_preferences already breaked down into dummies
# Mail Domain not usefull
# Geolocation only use Country
#df = df_original.copy()
df.drop(['Profile.Id','Year','Month', 'first_name','last_name','ebb_preferences','Domain', 'Geolocation.City','Geolocation.State','Geolocation.Zip'], axis = 1, inplace = True)
df.dtypes

Engagement                             object
Signup                         datetime64[ns]
Opens                                   int64
Clicks                                  int64
Last.Open                              object
Last.Click                             object
Optout.Time                            object
Geolocation.Country                    object
Lifetime.Message                        int64
Top.Device                             object
referral_source                        object
age                                   float64
gender                                 object
#ofPreferences                          int64
childrens                               int64
hist                                    int64
generalnonfiction                       int64
sciencefictionfantasy                   int64
bookclubpicks                           int64
historicalfiction                       int64
mysteriesthrillerstruecrime             int64
poetry                                  int64
romance                                 int64
bestsellers                             int64
biographyandmemoir                      int64
youngadult                              int64
literaryfiction                         int64
dtype: object

In [0]:
# Age and Gender has over 99% Na values drop them
df.drop(['age','gender'], axis = 1, inplace = True)

In [0]:
# Mange the datetime variables
# For the forecasting purpose round to day
df.Signup = df.Signup.dt.date
df['Optout.Time'] = pd.to_datetime(df['Optout.Time']).dt.date
df['Last.Open'] = pd.to_datetime(df['Last.Open']).dt.date
df['Last.Click'] = pd.to_datetime(df['Last.Click']).dt.date

In [0]:
#Covert Last Clicks and Last Open
#The duration between Last Clicks (Last Opens) and Sign up date makes more sense here.
df['Last.Open'] = (df['Last.Open'] - df['Signup']).dt.days
df['Last.Click'] = (df['Last.Click'] - df['Signup']).dt.days
# fill na using means
df['Last.Click'].fillna(0,inplace = True)
df['Last.Open'].fillna(0,inplace = True)

In [246]:
df['Top.Device'].isnull().mean()
df['Top.Device'].value_counts()

iPad                 45865
Android              44072
Chrome               43394
iPhone               38707
Android Tablet       31390
Firefox              18290
Internet Explorer    14546
Windows Tablet       12776
Safari                8543
Other                 5958
Windows Phone          179
Other Mobile           162
Nook                    90
Opera                   21
O:10:"D                 13
BlackBerry               8
Other Phone              6
Other Tablet             4
Nintendo                 3
Playstation              3
Thunderbird              3
Opera Mini               2
Name: Top.Device, dtype: int64

In [247]:
# Make All categories below Safari into other categories, Also Make Na value its own category
df['Top.Device'].fillna('Notknowdevice', inplace = True)
cate_keep = list(df['Top.Device'].value_counts().index[:10])+['Notknowdevice']
df['Top.Device'][~df['Top.Device'].isin(cate_keep)] = 'Otherdevice'

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [248]:
df['referral_source'].value_counts()

dmi                243435
facebook           147260
organicsource       75136
untagged            71084
liveintent          47852
torsweeps           20929
dmiqhealth          19352
inbookad            17859
fyntr               13795
permissiondata      11216
bookriot            10821
google               7327
humblebundle         2689
tlu                  2447
optint               2209
aramis               2132
sailthru             2084
bookpage             1395
tlucheckbox          1251
ebbembed              808
fbgiveaways           782
shelfawareness        695
welcomeemail          694
swagbucks             511
instafreebie          302
shelfie               211
noisetrade            188
bookbub               172
thelineup              86
readitforward          86
                    ...
warisboring            34
portalist              33
tiburon                23
worthbooks             20
emailcampaign          17
twitter                17
offtheshelf            14
jbfmembers             11
ebbv2                   9
reddit                  8
standarddisplay         7
ralphcom                5
litsy                   5
adroll                  5
taboola                 5
chickensoup             4
worth                   4
pinterest               4
bookstr                 4
tafemail                2
peachtree               2
test                    2
quora                   2
paypal                  1
cerkl                   1
earlybirdbooks          1
ralphtest               1
newvalue                1
viber                   1
dunkindonuts            1
Name: referral_source, Length: 62, dtype: int64

In [249]:
# Keep the first 12 categories (till google) group others into other
cate_keep = list(df['referral_source'].value_counts().index[:12])
df['referral_source'][~df['referral_source'].isin(cate_keep)] = 'Othersource'

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [250]:
#Country divided into US and non-US, and keep NA in its own category
df['Geolocation.Country'].fillna('Notknowcountry', inplace = True)
cate_keep = ['US','Notknowcountry']
df['Geolocation.Country'][~df['Geolocation.Country'].isin(cate_keep)] = 'Non-US'

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

### The Forecasting Model for Customer optout or not

To find when a customer is going to optout the newsleeter, we need first have a model to detect if the customer is going to churn or not. Then in the group of customers that have high possibility to chunk, we then use another model to determine when that churn will happen.

Therefore, in the first model to determine if it is going to churn or not, we use 'Engagement' to drive our target variable. And the 'Optout.Time' is not need in this model train.

In [0]:
Churn_df = df.drop(['Optout.Time', 'Signup'],axis =1)

In [0]:
Churn_df.Engagement = (Churn_df.Engagement == 'optout').astype(int)

In [253]:
Churn_df.head()

   Engagement  Opens  Clicks  ...  biographyandmemoir  youngadult literaryfiction
0           0     51      11  ...                   0           0               1
1           1      2       0  ...                   1           0               1
2           1      0       0  ...                   1           0               1
3           0      0       0  ...                   0           0               0
4           1     30       1  ...                   1           0               1

[5 rows x 23 columns]

**Above is the data for the churn detection model. The requirment is forecast when customers is going to optout, so skip the model here.**

### The prediction model for when a customers is going to optout

In [0]:
#Here we do not need the 'Engagement', because the training dataset now only contains customers that already optout.
Predict_df = df[df['Engagement'] == 'optout'].drop(['Engagement'],axis =1)
#The target variable here is the duration of time 
Predict_df['Optout.Time'] = (Predict_df['Optout.Time'] - Predict_df['Signup']).dt.days

In [0]:
Predict_df.dropna(subset=['Optout.Time'], inplace = True)
Predict_df.drop(['Signup'],axis = 1,inplace = True)

In [0]:
Predict_df.head()

    Opens  Clicks  ...  generalnonfiction  sciencefictionfantasy
1       2       0  ...                  1                      0
2       0       0  ...                  1                      0
4      30       1  ...                  1                      0
6      16       0  ...                  1                      0
10     31       5  ...                  1                      0

[5 rows x 23 columns]

**Try a Random forest model on the dataset**

In [0]:
#Covert categorical into dummies
country = pd.get_dummies(Predict_df['Geolocation.Country'])
referral = pd.get_dummies(Predict_df['referral_source'])
device = pd.get_dummies(Predict_df['Top.Device'])
RF_df = Predict_df.join([country,referral, device],how='inner').drop(['Geolocation.Country','referral_source','Top.Device'],axis = 1)

In [260]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import ShuffleSplit
y = RF_df['Optout.Time']
X = RF_df.drop(['Optout.Time'],axis = 1)
forest = RandomForestRegressor(n_estimators=50,max_features=2,max_depth = 10)
cvf = ShuffleSplit(n_splits=25, test_size=0.25)
scores = cross_val_score(forest, X, y, cv=cvf)
print(np.mean(scores))

0.7933686573445246

**Cross Validation Score (R square) in test set is about 80%**